FROM quay.io/jetstack/cert-manager-controller:laster
FROM quay.io/jetstack/cert-manager-webhook:laster
FROM quay.io/jetstack/cert-manager-acmesolver:laster
FROM quay.io/jetstack/cert-manager-ctl:laster