FROM quay.io/jetstack/cert-manager-controller:latest
FROM quay.io/jetstack/cert-manager-webhook:latest
FROM quay.io/jetstack/cert-manager-acmesolver:latest
FROM quay.io/jetstack/cert-manager-ctl:latest